In [1]:
# linear algebra library for python and is very fast and has binding to C libraries. Numpy arrays comes in vectors and matrices

In [2]:
# conda install numpy

In [3]:
my_list=[1,2,3]

In [4]:
import numpy as np

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrix=([1,2,3],[4,5,6],[7,8,9])

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)           # 2 is stepsize

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [14]:
np.zeros((5,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.linspace(0,5,10)          # (start,stop, space)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [17]:
np.linspace(0,5,15) 

array([ 0.        ,  0.35714286,  0.71428571,  1.07142857,  1.42857143,
        1.78571429,  2.14285714,  2.5       ,  2.85714286,  3.21428571,
        3.57142857,  3.92857143,  4.28571429,  4.64285714,  5.        ])

In [18]:
np.eye(4)            #identical matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
np.random.rand(5)

array([ 0.38570368,  0.37239243,  0.61482627,  0.40461235,  0.84661947])

In [20]:
np.random.rand(3,4)

array([[ 0.1317615 ,  0.91697996,  0.26811311,  0.86043204],
       [ 0.63758092,  0.52130137,  0.60451318,  0.58431109],
       [ 0.17779907,  0.45966375,  0.84870942,  0.22830575]])

In [21]:
np.random.randn(5)         # randn means random number

array([-0.29280674,  1.79946914,  0.03990843,  0.50110347, -0.0522411 ])

In [22]:
np.random.randn(3,5)

array([[ 1.58888807,  0.23896989,  0.96769247,  0.33855423,  1.06776677],
       [-1.04032575,  0.53238774,  0.01479767,  0.89314566,  1.0686001 ],
       [ 0.43919262,  1.04878957, -1.28071933,  0.84978445,  0.46938495]])

In [23]:
np.random.randint(1,100,10)          # low,high,size

array([44, 99, 87, 24, 46, 76, 59, 23, 36, 31])

In [25]:
arr=np.arange(20)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
ranarr=np.random.randint(0,50,10)

In [29]:
ranarr

array([25, 36, 13, 12, 44, 30, 12, 42, 44,  4])

In [30]:
arr.reshape(6,6)

ValueError: cannot reshape array of size 20 into shape (6,6)

In [31]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
ranarr.max()

44

In [33]:
ranarr.argmax()

4

In [38]:
arr=arr.reshape(4,5)

In [39]:
arr.shape

(4, 5)

In [41]:
arr.dtype          # its 32 bit integer

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2,10)

2

In [47]:
np.zeros(5) +5

array([ 5.,  5.,  5.,  5.,  5.])

In [48]:
np.ones(5) *5

array([ 5.,  5.,  5.,  5.,  5.])

In [49]:
np.linspace(0.1,1,100)

array([ 0.1       ,  0.10909091,  0.11818182,  0.12727273,  0.13636364,
        0.14545455,  0.15454545,  0.16363636,  0.17272727,  0.18181818,
        0.19090909,  0.2       ,  0.20909091,  0.21818182,  0.22727273,
        0.23636364,  0.24545455,  0.25454545,  0.26363636,  0.27272727,
        0.28181818,  0.29090909,  0.3       ,  0.30909091,  0.31818182,
        0.32727273,  0.33636364,  0.34545455,  0.35454545,  0.36363636,
        0.37272727,  0.38181818,  0.39090909,  0.4       ,  0.40909091,
        0.41818182,  0.42727273,  0.43636364,  0.44545455,  0.45454545,
        0.46363636,  0.47272727,  0.48181818,  0.49090909,  0.5       ,
        0.50909091,  0.51818182,  0.52727273,  0.53636364,  0.54545455,
        0.55454545,  0.56363636,  0.57272727,  0.58181818,  0.59090909,
        0.6       ,  0.60909091,  0.61818182,  0.62727273,  0.63636364,
        0.64545455,  0.65454545,  0.66363636,  0.67272727,  0.68181818,
        0.69090909,  0.7       ,  0.70909091,  0.71818182,  0.72

In [50]:
np.linspace(0.1,1,100).reshape(10,10)

array([[ 0.1       ,  0.10909091,  0.11818182,  0.12727273,  0.13636364,
         0.14545455,  0.15454545,  0.16363636,  0.17272727,  0.18181818],
       [ 0.19090909,  0.2       ,  0.20909091,  0.21818182,  0.22727273,
         0.23636364,  0.24545455,  0.25454545,  0.26363636,  0.27272727],
       [ 0.28181818,  0.29090909,  0.3       ,  0.30909091,  0.31818182,
         0.32727273,  0.33636364,  0.34545455,  0.35454545,  0.36363636],
       [ 0.37272727,  0.38181818,  0.39090909,  0.4       ,  0.40909091,
         0.41818182,  0.42727273,  0.43636364,  0.44545455,  0.45454545],
       [ 0.46363636,  0.47272727,  0.48181818,  0.49090909,  0.5       ,
         0.50909091,  0.51818182,  0.52727273,  0.53636364,  0.54545455],
       [ 0.55454545,  0.56363636,  0.57272727,  0.58181818,  0.59090909,
         0.6       ,  0.60909091,  0.61818182,  0.62727273,  0.63636364],
       [ 0.64545455,  0.65454545,  0.66363636,  0.67272727,  0.68181818,
         0.69090909,  0.7       ,  0.70909091

In [51]:
my_matrix=([1,2,3],[4,5,6],[7,8,9])

In [52]:
np.sum(my_matrix)

45

In [53]:
np.std(my_matrix)

2.5819888974716112