In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[7]

7

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [12]:
arr[0:5]=100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
slice_of_arr=arr[0:6]

In [16]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [17]:
slice_of_arr[:]=99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy=arr.copy()

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_2d[1][1]

5

In [26]:
arr_2d[2,2]

9

In [27]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr_2d[:1,2:]

array([[3]])

In [30]:
#conditional selection

In [32]:
arr=np.arange(11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr=arr > 5

In [36]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [37]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [38]:
arr[arr<3]

array([0, 1, 2])

In [42]:
arr_2d=np.arange(0,20).reshape(4,5)

In [43]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
arr_2d[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])